export const GET_ASYNC_DATA = 'GET_ACCESS_TOKEN';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const TOKEN_NOT_VALID = 'TOKEN_NOT_VALID'

export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const SAVE_USER_DATA_SUCCESS = 'SAVE_USER_DATA_SUCCESS';

export const INITIATE_GET_ASYNC_DATA = 'INITIATE_GET_ASYNC_DATA';
export const INITIATE_SET_ACCESS_TOKEN = 'INITIATE_SET_ACCESS_TOKEN';

export const INITIATE_GET_SHOW_CAUTION = 'INITIATE_GET_SHOW_CAUTION';
export const INITIATE_SET_SHOW_CAUTION = 'INITIATE_SET_SHOW_CAUTION';
export const GET_SHOW_CAUTION = 'GET_SHOW_CAUTION';
export const SET_SHOW_CAUTION = 'SET_SHOW_CAUTION';

export const START_SIGN_IN = 'START_SIGN_IN';

export const INTERNAL_ERROR = 'INTERNAL_ERROR';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_ADDITIONAL_USER_INFO = 'UPDATE_ADDITIONAL_USER_INFO';

export const GET_USER_CART_ITEMS = 'GET_USER_CART_ITEMS';
export const GET_USER_CART_ITEMS_SUCCESS = 'GET_USER_CART_ITEMS_SUCCESS';
export const GET_USER_BOOKMARK = 'GET_USER_BOOKMARK';
export const GET_USER_BOOKMARK_SUCCESS = 'GET_USER_BOOKMARK_SUCCESS';

export const ADD_USER_CART_ITEMS = 'ADD_USER_CART_ITEMS';
export const ADD_USER_CART_ITEMS_SUCCESS = 'ADD_USER_CART_ITEMS_SUCCESS';
export const SUB_CART_ITEMS = 'SUB_CART_ITEMS';
export const SUB_CART_ITEMS_SUCCESS = 'SUB_CART_ITEMS_SUCCESS';
export const REMOVE_CART_ITEMS_BY_ID = 'REMOVE_CART_ITEMS_BY_ID';
export const REMOVE_CART_ITEMS_BY_ID_SUCCESS =
  'REMOVE_CART_ITEMS_BY_ID_SUCCESS';
export const EMPTY_CART = 'EMPTY_CART';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';

export const SET_USER_BOOKMARK = 'SET_USER_BOOKMARK';
export const SET_USER_BOOKMARK_SUCCESS = 'SET_USER_BOOKMARK_SUCCESS';
export const SET_USER_SHARE = 'SET_USER_SHARE';
export const SET_USER_SHARE_SUCCESS = 'SET_USER_SHARE_SUCCESS';

export const GET_USER_ASYNC_PROFILE = 'GET_USER_ASYNC_PROFILE';
export const GET_USER_ASYNC_PROFILE_SUCCESS = 'GET_USER_ASYNC_PROFILE_SUCCESS';

export const REMOVE_BOOKMARK_BY_ID = 'REMOVE_BOOKMARK_BY_ID';
export const REMOVE_BOOKMARK_BY_ID_SUCCESS = 'REMOVE_BOOKMARK_BY_ID_SUCCESS';

export const HIDE_TOP_TABBAR = 'HIDE_TOP_TABBAR';

export const SHARE_URL = 'SHARE_URL';

export const ADD_TO_ADDRESS_LIST = 'ADD_TO_ADDRESS_LIST';
export const REMOVE_FROM_ADDRESS_LIST = 'REMOVE_FROM_ADDRESS_LIST';

export const GET_RECOMMENDAR_CAT_ID_ARRAYS = 'GET_RECOMMENDAR_CAT_ID_ARRAYS';
export const GET_RECOMMENDAR_CAT_ID_ARRAYS_SUCCESS =
  'GET_RECOMMENDAR_CAT_ID_ARRAYS_SUCCESS';
export const SET_RECOMMENDAR_CAT_ID_ARRAYS = 'SET_RECOMMENDAR_CAT_ID_ARRAYS';

export const SET_TICKET_STATE = "SET_TICKET_STATE"

export const TICKET_LIST = "TICKET_LIST"
export const SETUP_UP_TICKET_LIST = "SETUP_UP_TICKET_LIST"

export const SET_PRODUCTS_OF_MY_BUSINESS = "SET_PRODUCTS_OF_MY_BUSINESS"
export const ADD_NEW_PRODUCT_TO_LIST = "ADD_NEW_PRODUCT_TO_LIST"

export const SETUP_MY_BUSINESS = "SETUP_MY_BUSINESS"
export const ADD_NEW_TO_MY_BUSINESS = "ADD_NEW_TO_MY_BUSINESS"

export const LOGOUT = "LOGOUT"
export const NEW_FOLLOWED_BUSINESS = "NEW_FOLLOWED_BUSINESS"